name: Build

on:
  push:
    branches:
      - '*'
      - '!master'
    paths-ignore:
      - readme.md
      - README.md
      - CHANGELOG.md

  pull_request:
    branches:
      - master
      - develop

env:
  UI_BUILD_REACT: 'app/'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]

    steps:
      - name: Get Date
        run: 'echo "BUILD_DATE=`date +%FT%T%z`" >> $GITHUB_ENV'

      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: JS Build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

        run: |
          npm --prefix ${{ env.UI_BUILD_REACT }} ci
          npm --prefix ${{ env.UI_BUILD_REACT }} run lint
          npm --prefix ${{ env.UI_BUILD_REACT }} run test:coverage
          npm --prefix ${{ env.UI_BUILD_REACT }} run build

      - name: Codecov report
        uses: codecov/codecov-action@v1
